'use client';

// Exports every settled bet in a chosen date range as a plain-record PDF.
import { useState } from 'react';
import { Bet } from '@/lib/types';
import { SITE_NAME, CURRENCY_SYMBOL } from '@/lib/config';
import { exportReportPdf } from '@/lib/pdfReport';
import { SECTION, SECTION_TITLE, SELECT } from '../adminPanelStyles';

// Settled bets whose date falls within [from, to] (either bound optional), oldest first.
function betsInRange(bets: Bet[], from: Date | null, to: Date | null): Bet[] {
  return bets.filter((bet) => {
    const date = new Date(bet.date);

    if (from && date < from) {
      return false;
    }

    if (to && date > new Date(to.getTime() + 24 * 60 * 60 * 1000 - 1)) {
      return false;
    }

    return bet.result !== 'pending';
  }).sort((a, b) => +new Date(a.date) - +new Date(b.date));
}

function handleExport(bets: Bet[], rangeFrom: string, rangeTo: string) {
  const inRange = betsInRange(bets, rangeFrom ? new Date(rangeFrom) : null, rangeTo ? new Date(rangeTo) : null);

  exportReportPdf(
    'Bet Ledger',
    `${SITE_NAME} — ${rangeFrom || 'earliest'} to ${rangeTo || 'latest'}`,
    `Generated by ${SITE_NAME} — not tax advice`,
    ['Date', 'Title', 'Stake', 'Returns', 'P&L'],
    [80, 190, 70, 70, 70],
    inRange.map((bet) => {
      const pnl = (bet.returns ?? 0) - bet.stake;

      return [
        new Date(bet.date).toLocaleDateString('en-GB'), bet.title,
        `${CURRENCY_SYMBOL}${bet.stake.toFixed(2)}`, `${CURRENCY_SYMBOL}${(bet.returns ?? 0).toFixed(2)}`,
        `${pnl >= 0 ? '+' : ''}${CURRENCY_SYMBOL}${pnl.toFixed(2)}`,
      ];
    })
  );
}

export default function LedgerExportSection({ bets }: { bets: Bet[] }) {
  const [rangeFrom, setRangeFrom] = useState('');
  const [rangeTo, setRangeTo] = useState('');

  return (
    <div style={SECTION}>
      <p style={SECTION_TITLE}>DATE-RANGE LEDGER (PDF)</p>
      <p style={{ fontSize: 11.5, color: 'var(--text-faint)', marginBottom: 14, maxWidth: '55ch' }}>
        Export every settled bet in a chosen date range as a PDF — a plain record for your own books. Leave
        either date blank to leave that end open.
      </p>
      <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', alignItems: 'flex-end' }}>
        <div>
          <label style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--text-faint)', fontWeight: 700, display: 'block', marginBottom: 4 }}>FROM</label>
          <input type="date" value={rangeFrom} onChange={(event) => setRangeFrom(event.target.value)} style={SELECT} />
        </div>
        <div>
          <label style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--text-faint)', fontWeight: 700, display: 'block', marginBottom: 4 }}>TO</label>
          <input type="date" value={rangeTo} onChange={(event) => setRangeTo(event.target.value)} style={SELECT} />
        </div>
        <button onClick={() => handleExport(bets, rangeFrom, rangeTo)} style={{
          background: 'var(--accent)', border: 'none', borderRadius: 8, color: 'var(--accent-contrast)',
          fontSize: 13, fontWeight: 700, padding: '8px 16px', cursor: 'pointer',
        }}>
          Export as PDF
        </button>
      </div>
    </div>
  );
}
