'use client';

// Basic year-by-year stake/returns/P&L totals, with a PDF export — not tax advice,
// just a plain record to hand to whoever does your taxes.
import { Bet } from '@/lib/types';
import { SITE_NAME, CURRENCY_SYMBOL } from '@/lib/config';
import { formatUnits } from '@/lib/units';
import { taxByYear } from '@/lib/taxReport';
import { exportReportPdf } from '@/lib/pdfReport';
import { SECTION, SECTION_TITLE } from '../adminPanelStyles';

function handleExport(bets: Bet[]) {
  const years = taxByYear(bets);

  exportReportPdf(
    'Tax Report',
    `${SITE_NAME} — generated ${new Date().toLocaleDateString('en-GB')}`,
    `Generated by ${SITE_NAME} — not tax advice`,
    ['Year', 'Bets', 'Staked', 'Returns', 'P&L'],
    [80, 60, 90, 90, 90],
    years.map((year) => [String(year.year), String(year.bets), `${CURRENCY_SYMBOL}${year.staked.toFixed(2)}`, `${CURRENCY_SYMBOL}${year.returns.toFixed(2)}`, `${year.pnl >= 0 ? '+' : ''}${CURRENCY_SYMBOL}${year.pnl.toFixed(2)}`])
  );
}

export default function TaxReportSection({ bets }: { bets: Bet[] }) {
  const years = taxByYear(bets);

  return (
    <div style={SECTION}>
      <p style={SECTION_TITLE}>TAX REPORT (BASIC)</p>
      <p style={{ fontSize: 11.5, color: 'var(--text-faint)', marginBottom: 14, maxWidth: '55ch' }}>
        A simple year-by-year total of stakes, returns, and profit/loss from settled bets. This is not tax
        advice — check the rules that apply where you live.
      </p>
      {years.length > 0 && (
        <button onClick={() => handleExport(bets)} style={{
          background: 'transparent', border: '1px solid var(--border)', borderRadius: 8, color: 'var(--accent)',
          fontSize: 12, fontWeight: 600, padding: '7px 13px', cursor: 'pointer', marginBottom: 12,
        }}>
          Export as PDF
        </button>
      )}
      {years.length === 0 ? (
        <p style={{ fontSize: 12, color: 'var(--text-faint)' }}>No settled bets yet.</p>
      ) : (
        <div style={{ border: '1px solid var(--border)', borderRadius: 10, overflow: 'hidden' }}>
          <div style={{
            display: 'grid', gridTemplateColumns: '1fr 1fr 1fr 1fr 1fr', gap: 8, padding: '8px 12px',
            background: 'var(--surface-2)', fontFamily: 'var(--font-mono)', fontSize: 9, fontWeight: 700, color: 'var(--text-faint)', letterSpacing: '0.05em',
          }}>
            <span>YEAR</span><span style={{ textAlign: 'right' }}>BETS</span><span style={{ textAlign: 'right' }}>STAKED</span>
            <span style={{ textAlign: 'right' }}>RETURNS</span><span style={{ textAlign: 'right' }}>P&amp;L</span>
          </div>
          {years.map((year, index) => (
            <div key={year.year} style={{
              display: 'grid', gridTemplateColumns: '1fr 1fr 1fr 1fr 1fr', gap: 8, padding: '9px 12px',
              borderTop: index > 0 ? '1px solid var(--border-soft)' : undefined, alignItems: 'center',
            }}>
              <span className="tabular" style={{ fontFamily: 'var(--font-mono)', fontSize: 12.5, fontWeight: 700, color: 'var(--text)' }}>{year.year}</span>
              <span className="tabular" style={{ fontFamily: 'var(--font-mono)', fontSize: 11.5, color: 'var(--text-muted)', textAlign: 'right' }}>{year.bets}</span>
              <span className="tabular" style={{ fontFamily: 'var(--font-mono)', fontSize: 11.5, color: 'var(--text-muted)', textAlign: 'right' }}>{CURRENCY_SYMBOL}{year.staked.toFixed(2)}</span>
              <span className="tabular" style={{ fontFamily: 'var(--font-mono)', fontSize: 11.5, color: 'var(--text-muted)', textAlign: 'right' }}>{CURRENCY_SYMBOL}{year.returns.toFixed(2)}</span>
              <span className="tabular" style={{ fontFamily: 'var(--font-mono)', fontSize: 11.5, fontWeight: 700, textAlign: 'right', color: year.pnl >= 0 ? 'var(--won)' : 'var(--lost)' }}>
                {year.pnl >= 0 ? '+' : ''}{CURRENCY_SYMBOL}{year.pnl.toFixed(2)} <span style={{ fontWeight: 400, opacity: 0.7 }}>({formatUnits(year.pnl)})</span>
              </span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
