'use client';

import { useEffect, useState } from 'react';
import { Bet, FilterType } from '@/lib/types';
import { CURRENCY_SYMBOL, SITE_NAME } from '@/lib/config';
import { formatUnits } from '@/lib/units';
import AiGate from './AiGate';
import GoalAdmin from './GoalAdmin';

const SECTION: React.CSSProperties = {
  background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 14, padding: 16, marginBottom: 14,
};
const SECTION_TITLE: React.CSSProperties = {
  fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--accent)', fontWeight: 700, letterSpacing: '0.1em',
  marginBottom: 14, textTransform: 'uppercase',
};
const SELECT: React.CSSProperties = {
  background: 'var(--bg)', border: '1px solid var(--border)', borderRadius: 8,
  color: 'var(--text)', fontFamily: 'var(--font-body)', fontSize: 13, padding: '8px 10px', outline: 'none', cursor: 'pointer',
};

interface YearRow { year: number; bets: number; staked: number; returns: number; pnl: number; }

function taxByYear(bets: Bet[]): YearRow[] {
  const map = new Map<number, YearRow>();
  for (const b of bets) {
    if (b.result === 'pending') continue;
    const year = new Date(b.date).getFullYear();
    const row = map.get(year) ?? { year, bets: 0, staked: 0, returns: 0, pnl: 0 };
    row.bets += 1;
    row.staked += b.stake;
    const returns = b.returns ?? 0;
    row.returns += returns;
    row.pnl += returns - b.stake;
    map.set(year, row);
  }
  return Array.from(map.values()).sort((a, b) => b.year - a.year);
}

interface StoredSummary { text: string; period: string; generatedAt: string }

const PERIOD_OPTIONS: { value: FilterType; label: string }[] = [
  { value: 'last7', label: 'Last 7 Days' },
  { value: 'last30', label: 'Last 30 Days' },
  { value: 'last90', label: 'Last 90 Days' },
  { value: 'year', label: 'Last Year' },
  { value: 'all', label: 'All Time' },
];

// Renders a simple text/line table with jsPDF's core API — no autotable
// plugin, keeps the dependency footprint to just jsPDF for a "basic" export.
async function exportPdf(title: string, subtitle: string, columns: string[], colWidths: number[], rows: string[][]) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const marginX = 40;
  let y = 50;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(title, marginX, y);
  y += 18;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(subtitle, marginX, y);
  doc.setTextColor(0);
  y += 24;

  const rowHeight = 16;
  const pageHeight = doc.internal.pageSize.getHeight();

  function drawHeader() {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    let x = marginX;
    columns.forEach((col, i) => { doc.text(col, x, y); x += colWidths[i]; });
    y += 6;
    doc.setDrawColor(200);
    doc.line(marginX, y, marginX + colWidths.reduce((a, b) => a + b, 0), y);
    y += 12;
    doc.setFont('helvetica', 'normal');
  }

  drawHeader();
  for (const row of rows) {
    if (y > pageHeight - 50) {
      doc.addPage();
      y = 50;
      drawHeader();
    }
    let x = marginX;
    doc.setFontSize(8.5);
    row.forEach((cell, i) => { doc.text(cell, x, y, { maxWidth: colWidths[i] - 4 }); x += colWidths[i]; });
    y += rowHeight;
  }

  doc.setFontSize(7.5);
  doc.setTextColor(150);
  doc.text(`Generated by ${SITE_NAME} — not tax advice`, marginX, pageHeight - 24);

  doc.save(`${title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.pdf`);
}

export default function ReportsAdmin({ bets, aiEnabled }: { bets: Bet[]; aiEnabled: boolean | null }) {
  const [summary, setSummary] = useState<StoredSummary | null>(null);
  const [period, setPeriod] = useState<FilterType>('last30');
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState('');
  const [rangeFrom, setRangeFrom] = useState('');
  const [rangeTo, setRangeTo] = useState('');

  useEffect(() => {
    fetch('/api/admin/summary').then(r => r.ok ? r.json() : null).then(setSummary).catch(() => {});
  }, []);

  async function handleGenerate() {
    setGenerating(true);
    setError('');
    try {
      const res = await fetch('/api/admin/summary', {
        method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ period }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Failed to generate summary');
      setSummary(data);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to generate summary');
    } finally {
      setGenerating(false);
    }
  }

  const years = taxByYear(bets);

  function handleExportTaxPdf() {
    exportPdf(
      'Tax Report',
      `${SITE_NAME} — generated ${new Date().toLocaleDateString('en-GB')}`,
      ['Year', 'Bets', 'Staked', 'Returns', 'P&L'],
      [80, 60, 90, 90, 90],
      years.map(y => [String(y.year), String(y.bets), `${CURRENCY_SYMBOL}${y.staked.toFixed(2)}`, `${CURRENCY_SYMBOL}${y.returns.toFixed(2)}`, `${y.pnl >= 0 ? '+' : ''}${CURRENCY_SYMBOL}${y.pnl.toFixed(2)}`])
    );
  }

  function handleExportLedgerPdf() {
    const from = rangeFrom ? new Date(rangeFrom) : null;
    const to = rangeTo ? new Date(rangeTo) : null;
    const inRange = bets.filter(b => {
      const d = new Date(b.date);
      if (from && d < from) return false;
      if (to && d > new Date(to.getTime() + 24 * 60 * 60 * 1000 - 1)) return false;
      return b.result !== 'pending';
    }).sort((a, b) => +new Date(a.date) - +new Date(b.date));

    exportPdf(
      'Bet Ledger',
      `${SITE_NAME} — ${rangeFrom || 'earliest'} to ${rangeTo || 'latest'}`,
      ['Date', 'Title', 'Stake', 'Returns', 'P&L'],
      [80, 190, 70, 70, 70],
      inRange.map(b => {
        const pnl = (b.returns ?? 0) - b.stake;
        return [
          new Date(b.date).toLocaleDateString('en-GB'), b.title,
          `${CURRENCY_SYMBOL}${b.stake.toFixed(2)}`, `${CURRENCY_SYMBOL}${(b.returns ?? 0).toFixed(2)}`,
          `${pnl >= 0 ? '+' : ''}${CURRENCY_SYMBOL}${pnl.toFixed(2)}`,
        ];
      })
    );
  }

  return (
    <div>
      <GoalAdmin />

      <div style={SECTION}>
        <p style={SECTION_TITLE}>AI PERFORMANCE SUMMARY</p>
        <AiGate enabled={aiEnabled} anchor="ai-summary">
        <div style={{ display: 'flex', gap: 8, marginBottom: 12, flexWrap: 'wrap', alignItems: 'center' }}>
          <select value={period} onChange={e => setPeriod(e.target.value as FilterType)} style={SELECT}>
            {PERIOD_OPTIONS.map(p => <option key={p.value} value={p.value}>{p.label}</option>)}
          </select>
          <button onClick={handleGenerate} disabled={generating} style={{
            background: 'var(--accent)', border: 'none', borderRadius: 8, color: 'var(--accent-contrast)',
            fontSize: 13, fontWeight: 700, padding: '8px 16px', cursor: generating ? 'not-allowed' : 'pointer', opacity: generating ? 0.6 : 1,
          }}>
            {generating ? 'Generating…' : 'Generate Summary'}
          </button>
        </div>
        {error && <p style={{ fontSize: 12, color: 'var(--lost)', marginBottom: 10 }}>{error}</p>}
        {summary ? (
          <div style={{ background: 'var(--accent-soft)', border: '1px solid var(--accent)', borderRadius: 10, padding: '12px 14px' }}>
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: 9, fontWeight: 700, color: 'var(--accent)', letterSpacing: '0.06em', marginBottom: 6 }}>
              {summary.period.toUpperCase()}
            </div>
            <p style={{ fontSize: 13, color: 'var(--text)', lineHeight: 1.55 }}>{summary.text}</p>
            <div style={{ fontSize: 10, color: 'var(--text-faint)', marginTop: 8 }}>
              Generated {new Date(summary.generatedAt).toLocaleString('en-GB')}
            </div>
          </div>
        ) : (
          <p style={{ fontSize: 12, color: 'var(--text-faint)' }}>No summary generated yet.</p>
        )}
        </AiGate>
      </div>

      <div style={SECTION}>
        <p style={SECTION_TITLE}>TAX REPORT (BASIC)</p>
        <p style={{ fontSize: 11.5, color: 'var(--text-faint)', marginBottom: 14, maxWidth: '55ch' }}>
          A simple year-by-year total of stakes, returns, and profit/loss from settled bets. This is not tax
          advice — check the rules that apply where you live.
        </p>
        {years.length > 0 && (
          <button onClick={handleExportTaxPdf} style={{
            background: 'transparent', border: '1px solid var(--border)', borderRadius: 8, color: 'var(--accent)',
            fontSize: 12, fontWeight: 600, padding: '7px 13px', cursor: 'pointer', marginBottom: 12,
          }}>
            Export as PDF
          </button>
        )}
        {years.length === 0 ? (
          <p style={{ fontSize: 12, color: 'var(--text-faint)' }}>No settled bets yet.</p>
        ) : (
          <div style={{ border: '1px solid var(--border)', borderRadius: 10, overflow: 'hidden' }}>
            <div style={{
              display: 'grid', gridTemplateColumns: '1fr 1fr 1fr 1fr 1fr', gap: 8, padding: '8px 12px',
              background: 'var(--surface-2)', fontFamily: 'var(--font-mono)', fontSize: 9, fontWeight: 700, color: 'var(--text-faint)', letterSpacing: '0.05em',
            }}>
              <span>YEAR</span><span style={{ textAlign: 'right' }}>BETS</span><span style={{ textAlign: 'right' }}>STAKED</span>
              <span style={{ textAlign: 'right' }}>RETURNS</span><span style={{ textAlign: 'right' }}>P&amp;L</span>
            </div>
            {years.map((y, i) => (
              <div key={y.year} style={{
                display: 'grid', gridTemplateColumns: '1fr 1fr 1fr 1fr 1fr', gap: 8, padding: '9px 12px',
                borderTop: i > 0 ? '1px solid var(--border-soft)' : undefined, alignItems: 'center',
              }}>
                <span className="tabular" style={{ fontFamily: 'var(--font-mono)', fontSize: 12.5, fontWeight: 700, color: 'var(--text)' }}>{y.year}</span>
                <span className="tabular" style={{ fontFamily: 'var(--font-mono)', fontSize: 11.5, color: 'var(--text-muted)', textAlign: 'right' }}>{y.bets}</span>
                <span className="tabular" style={{ fontFamily: 'var(--font-mono)', fontSize: 11.5, color: 'var(--text-muted)', textAlign: 'right' }}>{CURRENCY_SYMBOL}{y.staked.toFixed(2)}</span>
                <span className="tabular" style={{ fontFamily: 'var(--font-mono)', fontSize: 11.5, color: 'var(--text-muted)', textAlign: 'right' }}>{CURRENCY_SYMBOL}{y.returns.toFixed(2)}</span>
                <span className="tabular" style={{ fontFamily: 'var(--font-mono)', fontSize: 11.5, fontWeight: 700, textAlign: 'right', color: y.pnl >= 0 ? 'var(--won)' : 'var(--lost)' }}>
                  {y.pnl >= 0 ? '+' : ''}{CURRENCY_SYMBOL}{y.pnl.toFixed(2)} <span style={{ fontWeight: 400, opacity: 0.7 }}>({formatUnits(y.pnl)})</span>
                </span>
              </div>
            ))}
          </div>
        )}
      </div>

      <div style={SECTION}>
        <p style={SECTION_TITLE}>DATE-RANGE LEDGER (PDF)</p>
        <p style={{ fontSize: 11.5, color: 'var(--text-faint)', marginBottom: 14, maxWidth: '55ch' }}>
          Export every settled bet in a chosen date range as a PDF — a plain record for your own books. Leave
          either date blank to leave that end open.
        </p>
        <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', alignItems: 'flex-end' }}>
          <div>
            <label style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--text-faint)', fontWeight: 700, display: 'block', marginBottom: 4 }}>FROM</label>
            <input type="date" value={rangeFrom} onChange={e => setRangeFrom(e.target.value)} style={SELECT} />
          </div>
          <div>
            <label style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--text-faint)', fontWeight: 700, display: 'block', marginBottom: 4 }}>TO</label>
            <input type="date" value={rangeTo} onChange={e => setRangeTo(e.target.value)} style={SELECT} />
          </div>
          <button onClick={handleExportLedgerPdf} style={{
            background: 'var(--accent)', border: 'none', borderRadius: 8, color: 'var(--accent-contrast)',
            fontSize: 13, fontWeight: 700, padding: '8px 16px', cursor: 'pointer',
          }}>
            Export as PDF
          </button>
        </div>
      </div>
    </div>
  );
}
